import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/Yekan-Bakh-Fa-04-Regular.ttf",
  variable: "--font-yekan-bakh",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/Yekan-Bakh-fat.ttf",
  variable: "--font-yekan-bakh-fat",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
